# screen constants
SCREEN_WIDTH = SCREEN_HEIGHT = 540
SCREEN_DIMENSIONS = SCREEN_WIDTH, SCREEN_HEIGHT
ROWS, COLUMNS = 30, 30
CUBE_HEIGHT, CUBE_WIDTH = SCREEN_HEIGHT / ROWS, SCREEN_WIDTH / COLUMNS
BG_COLOR = 36, 36, 36

# snake constants
SNAKE_COLOR = 40, 105, 107
FOOD_COLOR = 168, 0, 53
