# screen constants
SCREEN_WIDTH = SCREEN_HEIGHT = 540
SCREEN_DIMENSIONS = SCREEN_WIDTH, SCREEN_HEIGHT
ROWS, COLUMNS = 30, 30
CUBE_HEIGHT, CUBE_WIDTH = SCREEN_HEIGHT / ROWS, SCREEN_WIDTH / COLUMNS
BG_COLOR = 30, 30, 30

# snake constants
SNAKE_COLOR = 28, 102, 92

# food constants
FOOD_COLOR = 168, 0, 53
