# screen constants
SCREEN_WIDTH = SCREEN_HEIGHT = 540
SCREEN_DIMENSIONS = SCREEN_WIDTH, SCREEN_HEIGHT
ROWS, COLUMNS = 30, 30
CUBE_HEIGHT, CUBE_WIDTH = SCREEN_HEIGHT / ROWS, SCREEN_WIDTH / COLUMNS
BG_COLOR = 46, 51, 63

# snake constants
SNAKE_COLOR = 136, 192, 208

# food constants
FOOD_COLOR = 191, 97, 106
